export const grammarShortTheories: Record<string, string> = {
  "cau-truc-chu-ngu": "• Chủ ngữ (Subject) là chủ thể của hành động, thường là Danh từ (Noun), Đại từ (Pronoun), V-ing hoặc To-V.\n• Danh từ đếm được (Countable Nouns) có dạng số ít và số nhiều. Danh từ không đếm được (Uncountable Nouns) không có dạng số nhiều và luôn đi với động từ số ít.\n• Cần chú ý đến Sở hữu cách ('s) và cách sử dụng Mạo từ (a/an/the) trước danh từ.",
  "cac-thi-hien-tai": "• Hiện tại đơn (Present Simple): Diễn tả thói quen, chân lý, lịch trình cố định. (S + V/Vs/es).\n• Hiện tại tiếp diễn (Present Continuous): Hành động đang xảy ra tại thời điểm nói hoặc kế hoạch tương lai gần. (S + is/am/are + V-ing).\n• Hiện tại hoàn thành (Present Perfect): Hành động xảy ra trong quá khứ kéo dài đến hiện tại, hoặc vừa mới xảy ra để lại kết quả. (S + have/has + V3/ed).\n• Hiện tại hoàn thành tiếp diễn (Present Perfect Continuous): Nhấn mạnh quá trình liên tục của hành động kéo dài đến hiện tại.",
  "cac-thi-qua-khu-tuong-lai": "• Quá khứ đơn (Past Simple): Sự việc đã chấm dứt hoàn toàn trong quá khứ. (S + V2/ed).\n• Quá khứ tiếp diễn (Past Continuous): Hành động đang xảy ra tại một thời điểm cụ thể trong quá khứ. (S + was/were + V-ing).\n• Tương lai đơn (Future Simple): Quyết định tức thời, dự đoán không có căn cứ. (S + will + V).\n• Tương lai gần (Be going to): Dự định có sẵn hoặc dự đoán có căn cứ.",
  "su-hoa-hop-chu-vi": "• Chủ ngữ số ít đi với động từ số ít, chủ ngữ số nhiều đi với động từ số nhiều.\n• Hai chủ ngữ nối bằng 'and' thường chia số nhiều.\n• Nối bằng 'or', 'nor', 'either...or', 'neither...nor': Động từ chia theo chủ ngữ gần nhất.\n• Đại từ bất định (everyone, someone, nobody, everything...) luôn đi với động từ số ít.",
  "dai-tu": "• Đại từ nhân xưng: I, you, we, they, he, she, it (Làm chủ ngữ).\n• Đại từ tân ngữ: me, you, us, them, him, her, it (Đứng sau động từ hoặc giới từ).\n• Tính từ sở hữu: my, your, our, their, his, her, its (Luôn đứng trước Danh từ).\n• Đại từ sở hữu: mine, yours, ours, theirs, his, hers (Thay thế cho Tính từ sở hữu + Danh từ, không đi kèm Danh từ).\n• Đại từ phản thân: myself, yourself... (Chủ ngữ và tân ngữ là cùng một người/vật).",
  "dong-tu-tan-ngu": "• Theo sau bởi V-ing: enjoy, avoid, mind, admit, deny, consider, suggest, finish...\n• Theo sau bởi To-V: want, hope, decide, plan, promise, refuse, offer, expect...\n• Có thể đi với cả To-V và V-ing nhưng khác nghĩa: remember, forget, regret, stop, try.",
  "dong-tu-ban-khiem-khuyet": "• Need và Dare có 2 vai trò: có thể là Động từ thường hoặc Động từ khiếm khuyết.\n• Khi là động từ thường: Cần mượn trợ động từ (do/does/did) khi phủ định/nghi vấn, và theo sau là 'to V'.\n• Khi là động từ khiếm khuyết (thường trong câu phủ định/nghi vấn): Không dùng trợ động từ, theo sau là 'V-bare'. (Ví dụ: You needn't worry. / Dare he say it?).",
  "cau-hoi": "• Câu hỏi Yes/No: Đảo trợ động từ (Do/Does/Did/Is/Are/Will...) lên trước chủ ngữ.\n• Câu hỏi Wh- (What, Where, When, Why, Who, How...): Wh- + Trợ động từ + S + V?\n• Câu hỏi đuôi (Tag questions): Phía trước khẳng định -> đuôi phủ định. Phía trước phủ định -> đuôi khẳng định. (Ví dụ: You are a student, aren't you?).",
  "phu-hoa": "• Phụ họa khẳng định: Dùng 'So' hoặc 'Too'. \n  - Cấu trúc So: So + Trợ động từ + S. (Ví dụ: So do I / So am I).\n  - Cấu trúc Too: S + Trợ động từ, too. (Ví dụ: I do, too).\n• Phụ họa phủ định: Dùng 'Neither' hoặc 'Either'.\n  - Cấu trúc Neither: Neither + Trợ động từ + S.\n  - Cấu trúc Either: S + Trợ động từ (phủ định), either.",
  "menh-lenh-thuc": "• Mệnh lệnh khẳng định: Bắt đầu bằng một Động từ nguyên thể (V-bare). (Ví dụ: Stand up! / Please open the door).\n• Mệnh lệnh phủ định: Bắt đầu bằng Don't + V-bare. (Ví dụ: Don't talk in class!).\n• Cấu trúc Let's: Dùng để rủ rê. (Let's + V-bare = Chúng ta hãy...).",
  "dong-tu-khiem-khuyet": "• Động từ khiếm khuyết (Modal verbs) bao gồm: can, could, may, might, must, should, will, would...\n• Đặc điểm: Luôn đi kèm với động từ nguyên thể (V-bare) ở phía sau. Không thêm 's' hay 'es' dù chủ ngữ số ít.\n• Must: Bắt buộc từ chủ quan / Suy luận logic (must be).\n• Should / Ought to: Khuyên bảo.\n• Can / Could: Khả năng / Sự cho phép.",
  "cau-dieu-kien": "• Loại 1 (Có thật ở HT/TL): If + S + V(ht), S + will + V.\n• Loại 2 (Trái thực tế ở HT): If + S + V(qk/were), S + would/could + V.\n• Loại 3 (Trái thực tế ở QK): If + S + had + V3/ed, S + would/could + have + V3/ed.\n• Câu giả định (Subjunctive) với advise, demand, insist, suggest...: S1 + suggest + that + S2 + (should) + V-bare.",
  "cau-truc-as-if-hope-wish": "• As if / As though (Cứ như thể là): Đi với thì Quá khứ đơn (nếu trái thực tế hiện tại) hoặc Quá khứ hoàn thành (trái thực tế quá khứ).\n• Wish (Câu ước): \n  - Ước ở hiện tại: S + wish + S + V(qk).\n  - Ước ở quá khứ: S + wish + S + had + V3/ed.\n• Would rather (Thà... còn hơn): \n  - 1 chủ ngữ: S + would rather + V-bare.\n  - 2 chủ ngữ: S1 + would rather + S2 + V(qk).",
  "cau-truc-used-to-get-used-to": "• Used to + V-bare: Đã từng có thói quen làm gì trong quá khứ (nay không còn nữa).\n• Be used to + V-ing / Noun: Đã quen với việc gì đó ở hiện tại.\n• Get used to + V-ing / Noun: Đang dần làm quen với việc gì đó (nhấn mạnh vào quá trình thích nghi).",
  "tinh-tu-trang-tu": "• Tính từ (Adjective) đứng trước Danh từ hoặc sau Động từ liên kết (be, look, feel...). Trạng từ (Adverb) bổ nghĩa cho Động từ thường, Tính từ hoặc Trạng từ khác.\n• So sánh bằng: as + adj/adv + as.\n• So sánh hơn: adj-er/adv-er + than (từ ngắn) hoặc more + adj/adv + than (từ dài).\n• So sánh nhất: the + adj-est/adv-est (từ ngắn) hoặc the most + adj/adv (từ dài).",
  "cau-bi-dong": "• Câu bị động (Passive Voice) dùng để nhấn mạnh đối tượng bị tác động bởi hành động.\n• Công thức chung: Be + PII (Động từ to-be chia theo thì của câu chủ động).\n• Bị động với Modal verbs: Modal + be + PII.\n• Bị động đặc biệt với cấu trúc chủ ngữ giả (It is reported that...), hoặc động từ tri giác (see, hear...).",
  "dong-tu-gay-nguyen-nhan": "• Động từ gây nguyên nhân (Causative Verbs) dùng để diễn tả việc nhờ, sai khiến hoặc giúp đỡ ai đó làm gì.\n• Nhờ vả chủ động: Have sb DO sth / Get sb TO DO sth.\n• Nhờ vả bị động: Have/Get sth DONE (by sb).\n• Ép buộc/Cho phép: Make sb DO sth / Let sb DO sth.\n• Giúp đỡ: Help sb DO sth (hoặc Help sb TO DO sth).",
  "menh-de-quan-he": "• Đại từ quan hệ: Who (người, S/O), Whom (người, O), Which (vật), That (người/vật), Whose (sở hữu).\n• Trạng từ quan hệ: Where (nơi chốn), When (thời gian), Why (lý do).\n• Rút gọn mệnh đề quan hệ: Dùng V-ing (chủ động), PII (bị động), hoặc To-V (sau the first, the last, the only...).",
  "lien-tu": "• Liên từ kết hợp (Coordinating Conjunctions): AND, BUT, OR, SO... dùng để nối 2 từ, 2 cụm từ hoặc 2 mệnh đề tương đương nhau.\n• Liên từ phụ thuộc (Subordinating Conjunctions): BECAUSE, ALTHOUGH, WHEN, WHILE, UNLESS... đứng trước mệnh đề phụ để nối nó với mệnh đề chính.\n• Tương quan liên từ (Correlative Conjunctions): BOTH... AND, EITHER... OR, NEITHER... NOR, NOT ONLY... BUT ALSO luôn đi theo cặp.",
  "gioi-tu": "• Giới từ chỉ thời gian: IN (tháng, năm, mùa), ON (thứ, ngày lễ), AT (giờ, khoảnh khắc cụ thể).\n• Giới từ chỉ nơi chốn: IN (trong một không gian rộng), ON (trên bề mặt), AT (tại một địa điểm cụ thể).\n• Một số giới từ thường đi kèm Động từ/Tính từ cần học thuộc: dependent ON, capable OF, interested IN, succeed IN, apologize TO.",
  "cau-truc-tiep-gian-tiep": "• Khi chuyển từ Câu trực tiếp sang Câu gián tiếp (Reported Speech), cần thực hiện 3 bước: Lùi 1 thì (HT -> QK, QK -> QKHT...), Đổi đại từ nhân xưng/tân ngữ/sở hữu, Đổi trạng từ chỉ thời gian/nơi chốn (now -> then, here -> there, yesterday -> the day before...).\n• Câu hỏi Yes/No: Dùng if / whether.\n• Câu hỏi Wh-: Giữ nguyên từ để hỏi, theo sau là Chủ ngữ + Động từ (đã lùi thì).\n• Mệnh lệnh: tell/ask/order + sb + (not) to V.",
  "tu-chi-so-luong-mao-tu": "• Mạo từ A/An: Dùng trước Danh từ đếm được số ít, chưa xác định. 'An' đứng trước từ bắt đầu bằng nguyên âm (u, e, o, a, i).\n• Mạo từ The: Dùng trước Danh từ đã được xác định, vật duy nhất (the sun), so sánh nhất, hoặc nhóm người (the poor).\n• Some / Any: 'Some' dùng trong câu khẳng định và câu mời mọc. 'Any' dùng trong câu phủ định và câu hỏi.\n• Much / Little: Đi với Danh từ không đếm được.\n• Many / Few: Đi với Danh từ đếm được số nhiều.",
  "phan-tu-va-cum-phan-tu": "• Hiện tại phân từ (V-ing): Mang nghĩa chủ động hoặc đang diễn ra (Ví dụ: falling leaves = lá đang rơi). Dùng để rút gọn mệnh đề quan hệ chủ động.\n• Quá khứ phân từ (V-ed/P2): Mang nghĩa bị động hoặc đã hoàn tất (Ví dụ: fallen leaves = lá đã rụng). Dùng để rút gọn mệnh đề quan hệ bị động.\n• Phân từ hoàn thành (Having + P2): Nhấn mạnh hành động đã xảy ra và hoàn tất trước một hành động khác trong quá khứ.",
  "cau-truc-dao-ngu": "• Đảo ngữ với từ phủ định (Never, Rarely, Seldom, Hardly, Little...): Đưa Trợ động từ lên trước Chủ ngữ (Ví dụ: Never have I seen...).\n• Đảo ngữ No sooner... than / Hardly... when: Vừa mới... thì...\n• Đảo ngữ câu điều kiện: Bỏ If. Loại 1 (Should S V), Loại 2 (Were S... / Were S to V), Loại 3 (Had S P2).\n• Đảo ngữ toàn bộ: Đưa Trạng từ chỉ nơi chốn/phương hướng lên đầu, Động từ giữ nguyên không mượn Trợ động từ (Ví dụ: Here comes the bus).",
  // Dành cho các topic cũ
  "relative-clause": "• Đại từ quan hệ (Who/Whom/Which/That/Whose) thay thế cho danh từ đứng trước nó để tạo thành Mệnh đề quan hệ.\n• Who: Chỉ người (làm Chủ ngữ/Tân ngữ).\n• Whom: Chỉ người (chỉ làm Tân ngữ).\n• Which: Chỉ vật.\n• That: Thay thế cho Who/Whom/Which trong mệnh đề xác định.\n• Whose: Chỉ sự sở hữu.",
  "participle-adjective": "• Tính từ đuôi -ING (V-ing): Dùng để miêu tả bản chất, đặc điểm của người/vật/sự việc (Ví dụ: The movie is boring).\n• Tính từ đuôi -ED (V-ed): Dùng để miêu tả cảm xúc, trạng thái của người do bị tác động (Ví dụ: I am bored).\n• Trong bài thi TOEIC, chú ý phân biệt khi nào từ đóng vai trò tính từ, khi nào là phân từ trong thì tiếp diễn/hoàn thành.",
  "simple-past": "• Quá khứ đơn (Past Simple) diễn tả hành động đã xảy ra và chấm dứt hoàn toàn trong quá khứ.\n• Công thức khẳng định: S + V2/ed. \n• Phủ định: S + didn't + V-bare.\n• Nghi vấn: Did + S + V-bare?\n• Dấu hiệu nhận biết: yesterday, last (week/month/year), (2 days) ago, in 1990...",
  "word-form": "• Cấu tạo từ (Word Form) là một phần vô cùng quan trọng trong TOEIC Part 5.\n• Quy tắc vị trí:\n  - Danh từ: Đứng sau Mạo từ (a/an/the), Tính từ, Giới từ.\n  - Tính từ: Đứng trước Danh từ bổ nghĩa, hoặc sau Tobe / Linking verbs (look, seem...).\n  - Trạng từ: Bổ nghĩa cho Động từ thường, Tính từ, Trạng từ khác, hoặc cả câu (thường có đuôi -ly).\n  - Động từ: Đứng sau Chủ ngữ.",
  "cau-dao-ngu": "• Đảo ngữ (Inversion) là việc đưa Trợ động từ lên trước Chủ ngữ để nhấn mạnh.\n• Các dạng phổ biến:\n  - Đảo ngữ với từ phủ định: Never, Rarely, Seldom, Hardly, Scarcely... (Ví dụ: Never have I seen such a beautiful view).\n  - Đảo ngữ với No sooner... than / Hardly... when.\n  - Đảo ngữ với Only (Only then, Only when...).\n  - Câu điều kiện đảo ngữ (Bỏ If, đảo Had / Were / Should lên đầu)."
};

export function getShortTheory(slug: string): string {
  const baseSlug = slug.replace(/-(co-ban|trung-cap|nang-cao)$/, '');
  return grammarShortTheories[baseSlug] || "Hãy bắt đầu làm bài tập ngay để rèn luyện kỹ năng ngữ pháp của bạn. Nếu gặp câu hỏi khó, đừng ngần ngại xem phần giải thích chi tiết phía sau mỗi câu nhé!";
}
