import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const basicVocabs = [
  {
    word: 'Doctor',
    phonetic: '/ˈdɑːktər/',
    meaning: 'Bác sĩ',
    englishDefinition: 'A person who is qualified to treat people who are ill.',
    example: 'The doctor advised him to get plenty of rest.',
    exampleVi: 'Bác sĩ khuyên anh ấy nên nghỉ ngơi nhiều.',
    synonyms: 'physician, medical practitioner',
    antonyms: '(Blank)',
    collocations: 'see a doctor, doctor’s appointment',
    toeicTrap: 'Chú ý phân biệt "doctor" (bác sĩ) và "dentist" (nha sĩ) trong bài nghe Part 2/3.',
  },
  {
    word: 'Hospital',
    phonetic: '/ˈhɑːspɪtl/',
    meaning: 'Bệnh viện',
    englishDefinition: 'An institution providing medical and surgical treatment and nursing care for sick or injured people.',
    example: 'She is recovering in the hospital after her surgery.',
    exampleVi: 'Cô ấy đang hồi phục trong bệnh viện sau ca phẫu thuật.',
    synonyms: 'clinic, medical center',
    antonyms: '(Blank)',
    collocations: 'admit to a hospital, discharge from a hospital',
    toeicTrap: 'Từ này thường đi kèm với các giới từ như "in the hospital" hoặc "at the hospital".',
  },
  {
    word: 'Patient',
    phonetic: '/ˈpeɪʃnt/',
    meaning: 'Bệnh nhân',
    englishDefinition: 'A person receiving or registered to receive medical treatment.',
    example: 'The hospital is currently treating over 500 patients.',
    exampleVi: 'Bệnh viện hiện đang điều trị cho hơn 500 bệnh nhân.',
    synonyms: 'sick person, sufferer',
    antonyms: '(Blank)',
    collocations: 'examine a patient, treat a patient',
    toeicTrap: 'Lưu ý "patient" còn là tính từ mang nghĩa "kiên nhẫn".',
  },
  {
    word: 'Medicine',
    phonetic: '/ˈmedɪsn/',
    meaning: 'Thuốc, y học',
    englishDefinition: 'A compound or preparation used for the treatment or prevention of disease.',
    example: 'Did you take your medicine this morning?',
    exampleVi: 'Sáng nay bạn đã uống thuốc chưa?',
    synonyms: 'medication, drug, cure',
    antonyms: '(Blank)',
    collocations: 'take medicine, prescribe medicine',
    toeicTrap: 'Thường bị nhầm với "medical" (tính từ: thuộc về y tế).',
  },
  {
    word: 'Nurse',
    phonetic: '/nɜːrs/',
    meaning: 'Y tá',
    englishDefinition: 'A person trained to care for the sick or infirm, especially in a hospital.',
    example: 'The nurse came in to check his blood pressure.',
    exampleVi: 'Y tá bước vào để kiểm tra huyết áp của anh ấy.',
    synonyms: 'caregiver',
    antonyms: '(Blank)',
    collocations: 'registered nurse, head nurse',
    toeicTrap: '(Blank)',
  },
  {
    word: 'Health',
    phonetic: '/helθ/',
    meaning: 'Sức khỏe',
    englishDefinition: 'The state of being free from illness or injury.',
    example: 'Regular exercise is good for your health.',
    exampleVi: 'Tập thể dục thường xuyên rất tốt cho sức khỏe của bạn.',
    synonyms: 'well-being, fitness',
    antonyms: 'illness, sickness',
    collocations: 'good health, health insurance, health care',
    toeicTrap: 'Chú ý cụm "health insurance" (bảo hiểm y tế) rất hay xuất hiện trong Part 7.',
  },
  {
    word: 'Pain',
    phonetic: '/peɪn/',
    meaning: 'Sự đau đớn',
    englishDefinition: 'Highly unpleasant physical sensation caused by illness or injury.',
    example: 'He felt a sharp pain in his chest.',
    exampleVi: 'Anh ấy cảm thấy một cơn đau nhói ở ngực.',
    synonyms: 'ache, agony, suffering',
    antonyms: 'comfort, relief',
    collocations: 'feel pain, relieve pain, sharp pain',
    toeicTrap: 'Cẩn thận nhầm lẫn với "paint" (sơn) trong Part 1.',
  },
  {
    word: 'Sick',
    phonetic: '/sɪk/',
    meaning: 'Ốm, bệnh',
    englishDefinition: 'Affected by physical or mental illness.',
    example: 'He called in sick to work today.',
    exampleVi: 'Hôm nay anh ấy đã gọi điện xin nghỉ ốm.',
    synonyms: 'ill, unwell',
    antonyms: 'healthy, well',
    collocations: 'call in sick, feel sick, fall sick',
    toeicTrap: 'Cụm "call in sick" (gọi điện xin nghỉ ốm) cực kỳ phổ biến trong môi trường công sở TOEIC.',
  },
  {
    word: 'Cure',
    phonetic: '/kjʊr/',
    meaning: 'Chữa trị, phương thuốc',
    englishDefinition: 'Relieve a person or animal of the symptoms of a disease or condition.',
    example: 'Scientists are trying to find a cure for cancer.',
    exampleVi: 'Các nhà khoa học đang cố gắng tìm ra cách chữa bệnh ung thư.',
    synonyms: 'heal, remedy, treatment',
    antonyms: '(Blank)',
    collocations: 'find a cure, completely cured',
    toeicTrap: '(Blank)',
  },
  {
    word: 'Diet',
    phonetic: '/ˈdaɪət/',
    meaning: 'Chế độ ăn uống',
    englishDefinition: 'The kinds of food that a person, animal, or community habitually eats.',
    example: 'A healthy diet is essential for losing weight.',
    exampleVi: 'Một chế độ ăn uống lành mạnh là rất cần thiết để giảm cân.',
    synonyms: 'nutrition, eating habits',
    antonyms: '(Blank)',
    collocations: 'healthy diet, go on a diet, balanced diet',
    toeicTrap: '"Diet" không chỉ có nghĩa là "ăn kiêng" mà còn là "chế độ ăn uống" nói chung.',
  },
  {
    word: 'Clinic',
    phonetic: '/ˈklɪnɪk/',
    meaning: 'Phòng khám',
    englishDefinition: 'An establishment or hospital department where outpatients are given medical treatment or advice.',
    example: 'She went to the local clinic for a check-up.',
    exampleVi: 'Cô ấy đã đến phòng khám địa phương để kiểm tra sức khỏe.',
    synonyms: 'health center, infirmary',
    antonyms: '(Blank)',
    collocations: 'medical clinic, dental clinic',
    toeicTrap: '(Blank)',
  },
  {
    word: 'Disease',
    phonetic: '/dɪˈziːz/',
    meaning: 'Căn bệnh',
    englishDefinition: 'A disorder of structure or function in a human, animal, or plant.',
    example: 'Heart disease is a major problem in many countries.',
    exampleVi: 'Bệnh tim là một vấn đề lớn ở nhiều quốc gia.',
    synonyms: 'illness, sickness, condition',
    antonyms: 'health',
    collocations: 'prevent disease, catch a disease, fatal disease',
    toeicTrap: 'Đừng nhầm lẫn với "decease" (sự qua đời).',
  },
  {
    word: 'Symptom',
    phonetic: '/ˈsɪmptəm/',
    meaning: 'Triệu chứng',
    englishDefinition: 'A physical or mental feature which is regarded as indicating a condition of disease.',
    example: 'A high fever is a common symptom of the flu.',
    exampleVi: 'Sốt cao là một triệu chứng phổ biến của bệnh cúm.',
    synonyms: 'sign, indication',
    antonyms: '(Blank)',
    collocations: 'flu symptoms, show symptoms, relieve symptoms',
    toeicTrap: '(Blank)',
  },
  {
    word: 'Pharmacy',
    phonetic: '/ˈfɑːrməsi/',
    meaning: 'Tiệm thuốc, hiệu thuốc',
    englishDefinition: 'A shop or hospital dispensary where medicinal drugs are prepared or sold.',
    example: 'You can buy this medicine at any pharmacy.',
    exampleVi: 'Bạn có thể mua loại thuốc này ở bất kỳ hiệu thuốc nào.',
    synonyms: 'drugstore, chemist',
    antonyms: '(Blank)',
    collocations: 'local pharmacy, go to the pharmacy',
    toeicTrap: 'Trong bài nghe Anh-Anh thường dùng từ "chemist" thay cho "pharmacy".',
  },
  {
    word: 'Checkup',
    phonetic: '/ˈtʃek ʌp/',
    meaning: 'Sự kiểm tra sức khỏe',
    englishDefinition: 'A thorough medical or dental examination.',
    example: 'I need to schedule an annual dental checkup.',
    exampleVi: 'Tôi cần lên lịch kiểm tra nha khoa hàng năm.',
    synonyms: 'examination, inspection',
    antonyms: '(Blank)',
    collocations: 'annual checkup, routine checkup, medical checkup',
    toeicTrap: 'Thường đi với động từ "schedule", "have", "go for".',
  }
];

const advancedVocabs = [
  {
    word: 'Physician',
    phonetic: '/fɪˈzɪʃn/',
    meaning: 'Bác sĩ (thường là nội khoa)',
    englishDefinition: 'A person qualified to practice medicine, especially one who specializes in diagnosis and medical treatment as distinct from surgery.',
    example: 'Please consult your physician before starting any new exercise routine.',
    exampleVi: 'Vui lòng tham khảo ý kiến bác sĩ của bạn trước khi bắt đầu bất kỳ thói quen tập thể dục mới nào.',
    synonyms: 'doctor, medical practitioner',
    antonyms: '(Blank)',
    collocations: 'attending physician, family physician, primary care physician',
    toeicTrap: 'Thường bị nhầm phát âm với "physicist" (nhà vật lý học). Đừng nhầm lẫn khi nghe!',
  },
  {
    word: 'Prescription',
    phonetic: '/prɪˈskrɪpʃn/',
    meaning: 'Đơn thuốc',
    englishDefinition: 'An instruction written by a medical practitioner that authorizes a patient to be provided a medicine or treatment.',
    example: 'The doctor gave me a prescription for antibiotics.',
    exampleVi: 'Bác sĩ đã kê cho tôi một đơn thuốc kháng sinh.',
    synonyms: 'instruction, remedy',
    antonyms: '(Blank)',
    collocations: 'fill a prescription, write a prescription, prescription drug',
    toeicTrap: 'Thường gặp trong Part 3/4 ở ngữ cảnh nhà thuốc (pharmacy). "Fill a prescription" nghĩa là "lấy thuốc theo đơn".',
  },
  {
    word: 'Diagnosis',
    phonetic: '/ˌdaɪəɡˈnoʊsɪs/',
    meaning: 'Sự chẩn đoán',
    englishDefinition: 'The identification of the nature of an illness or other problem by examination of the symptoms.',
    example: 'Early diagnosis and treatment are essential.',
    exampleVi: 'Việc chẩn đoán và điều trị sớm là rất cần thiết.',
    synonyms: 'identification, assessment',
    antonyms: '(Blank)',
    collocations: 'accurate diagnosis, medical diagnosis, confirm a diagnosis',
    toeicTrap: 'Lưu ý dạng số nhiều là "diagnoses" (/ˌdaɪəɡˈnoʊsiːz/).',
  },
  {
    word: 'Chronic',
    phonetic: '/ˈkrɑːnɪk/',
    meaning: 'Mãn tính, kinh niên',
    englishDefinition: '(Of an illness) persisting for a long time or constantly recurring.',
    example: 'The clinic specializes in the treatment of chronic back pain.',
    exampleVi: 'Phòng khám chuyên điều trị chứng đau lưng mãn tính.',
    synonyms: 'persistent, long-lasting, constant',
    antonyms: 'acute, temporary',
    collocations: 'chronic disease, chronic pain, chronic condition',
    toeicTrap: '(Blank)',
  },
  {
    word: 'Alleviate',
    phonetic: '/əˈliːvieɪt/',
    meaning: 'Làm giảm bớt (đau đớn)',
    englishDefinition: 'Make (suffering, deficiency, or a problem) less severe.',
    example: 'The medication will help to alleviate the symptoms.',
    exampleVi: 'Thuốc sẽ giúp làm giảm các triệu chứng.',
    synonyms: 'relieve, ease, lessen, mitigate',
    antonyms: 'aggravate, worsen',
    collocations: 'alleviate pain, alleviate symptoms, alleviate suffering',
    toeicTrap: '(Blank)',
  },
  {
    word: 'Surgery',
    phonetic: '/ˈsɜːrdʒəri/',
    meaning: 'Phẫu thuật',
    englishDefinition: 'The medical treatment of injuries or diseases that involves cutting open a person\'s body.',
    example: 'He will require surgery on his left knee.',
    exampleVi: 'Anh ấy sẽ cần phẫu thuật ở đầu gối trái.',
    synonyms: 'operation, medical procedure',
    antonyms: '(Blank)',
    collocations: 'undergo surgery, perform surgery, minor/major surgery',
    toeicTrap: '(Blank)',
  },
  {
    word: 'Immune',
    phonetic: '/ɪˈmjuːn/',
    meaning: 'Miễn dịch',
    englishDefinition: 'Resistant to a particular infection or toxin owing to the presence of specific antibodies or sensitized white blood cells.',
    example: 'The vaccine makes you immune to the virus.',
    exampleVi: 'Vắc-xin giúp bạn miễn dịch với vi-rút.',
    synonyms: 'resistant, protected',
    antonyms: 'susceptible, vulnerable',
    collocations: 'immune system, immune response, become immune',
    toeicTrap: '(Blank)',
  },
  {
    word: 'Therapy',
    phonetic: '/ˈθerəpi/',
    meaning: 'Liệu pháp, sự điều trị',
    englishDefinition: 'Treatment intended to relieve or heal a disorder.',
    example: 'She is undergoing physical therapy after her accident.',
    exampleVi: 'Cô ấy đang trải qua vật lý trị liệu sau tai nạn.',
    synonyms: 'treatment, remedy, cure',
    antonyms: '(Blank)',
    collocations: 'physical therapy, undergo therapy, group therapy',
    toeicTrap: 'Nhà trị liệu sẽ là "therapist".',
  },
  {
    word: 'Complication',
    phonetic: '/ˌkɑːmplɪˈkeɪʃn/',
    meaning: 'Biến chứng, sự phức tạp',
    englishDefinition: 'A secondary disease or condition aggravating an already existing one.',
    example: 'She developed complications after the surgery.',
    exampleVi: 'Cô ấy đã phát triển các biến chứng sau phẫu thuật.',
    synonyms: 'difficulty, problem',
    antonyms: '(Blank)',
    collocations: 'medical complications, post-operative complications',
    toeicTrap: '(Blank)',
  },
  {
    word: 'Fatigue',
    phonetic: '/fəˈtiːɡ/',
    meaning: 'Sự mệt mỏi rã rời',
    englishDefinition: 'Extreme tiredness resulting from mental or physical exertion or illness.',
    example: 'The doctor said that her fatigue was caused by stress.',
    exampleVi: 'Bác sĩ nói rằng sự mệt mỏi của cô ấy là do căng thẳng.',
    synonyms: 'tiredness, exhaustion, weariness',
    antonyms: 'energy, vigor',
    collocations: 'mental fatigue, suffer from fatigue, chronic fatigue',
    toeicTrap: '(Blank)',
  },
  {
    word: 'Epidemic',
    phonetic: '/ˌepɪˈdemɪk/',
    meaning: 'Bệnh dịch',
    englishDefinition: 'A widespread occurrence of an infectious disease in a community at a particular time.',
    example: 'The city is currently facing a flu epidemic.',
    exampleVi: 'Thành phố hiện đang phải đối mặt với một trận dịch cúm.',
    synonyms: 'outbreak, plague',
    antonyms: '(Blank)',
    collocations: 'flu epidemic, global epidemic, prevent an epidemic',
    toeicTrap: 'Cấp độ cao hơn của "epidemic" là "pandemic" (đại dịch toàn cầu).',
  },
  {
    word: 'Preventative',
    phonetic: '/prɪˈventətɪv/',
    meaning: 'Ngăn ngừa, phòng ngừa',
    englishDefinition: 'Designed to keep something undesirable such as illness, harm, or accidents from occurring.',
    example: 'Preventative medicine focuses on maintaining health to avoid disease.',
    exampleVi: 'Y học phòng ngừa tập trung vào việc duy trì sức khỏe để tránh bệnh tật.',
    synonyms: 'preventive, protective, precautionary',
    antonyms: '(Blank)',
    collocations: 'preventative measures, preventative care, preventative maintenance',
    toeicTrap: 'Thường xuất hiện trong bài đọc liên quan đến chính sách y tế của công ty.',
  },
  {
    word: 'Vaccination',
    phonetic: '/ˌvæksɪˈneɪʃn/',
    meaning: 'Sự tiêm chủng',
    englishDefinition: 'Treatment with a vaccine to produce immunity against a disease.',
    example: 'All employees are required to get a flu vaccination.',
    exampleVi: 'Tất cả nhân viên được yêu cầu tiêm phòng cúm.',
    synonyms: 'inoculation, immunization, injection',
    antonyms: '(Blank)',
    collocations: 'flu vaccination, mandatory vaccination',
    toeicTrap: '(Blank)',
  },
  {
    word: 'Hygiene',
    phonetic: '/ˈhaɪdʒiːn/',
    meaning: 'Vệ sinh',
    englishDefinition: 'Conditions or practices conducive to maintaining health and preventing disease, especially through cleanliness.',
    example: 'Proper dental hygiene is important for preventing tooth decay.',
    exampleVi: 'Vệ sinh răng miệng đúng cách rất quan trọng để ngăn ngừa sâu răng.',
    synonyms: 'cleanliness, sanitation',
    antonyms: '(Blank)',
    collocations: 'personal hygiene, poor hygiene, maintain hygiene',
    toeicTrap: '(Blank)',
  },
  {
    word: 'Adverse',
    phonetic: '/ədˈvɜːrs/',
    meaning: 'Bất lợi, có hại',
    englishDefinition: 'Preventing success or development; harmful; unfavorable.',
    example: 'The drug may cause adverse side effects in some patients.',
    exampleVi: 'Thuốc có thể gây ra các tác dụng phụ bất lợi ở một số bệnh nhân.',
    synonyms: 'unfavorable, negative, harmful',
    antonyms: 'favorable, positive, beneficial',
    collocations: 'adverse effects, adverse reaction, adverse conditions',
    toeicTrap: 'Đừng nhầm với "averse" (ác cảm). Cụm "adverse effects" xuất hiện rất thường xuyên trong TOEIC Reading.',
  }
];

const mixedVocabs = [
  // 7 Basic
  {
    word: 'Dentist',
    phonetic: '/ˈdentɪst/',
    meaning: 'Nha sĩ',
    englishDefinition: 'A person qualified to treat the diseases and conditions that affect the teeth and gums.',
    example: 'I have an appointment with the dentist tomorrow.',
    exampleVi: 'Tôi có cuộc hẹn với nha sĩ vào ngày mai.',
    synonyms: 'dental surgeon',
    antonyms: '(Blank)',
    collocations: 'see a dentist, visit the dentist',
    toeicTrap: '(Blank)',
  },
  {
    word: 'Blood',
    phonetic: '/blʌd/',
    meaning: 'Máu',
    englishDefinition: 'The red liquid that circulates in the arteries and veins of humans and other vertebrate animals.',
    example: 'He lost a lot of blood in the accident.',
    exampleVi: 'Anh ấy đã mất rất nhiều máu trong vụ tai nạn.',
    synonyms: '(Blank)',
    antonyms: '(Blank)',
    collocations: 'blood pressure, blood test, donate blood',
    toeicTrap: '(Blank)',
  },
  {
    word: 'Headache',
    phonetic: '/ˈhedeɪk/',
    meaning: 'Đau đầu',
    englishDefinition: 'A continuous pain in the head.',
    example: 'I had a terrible headache all morning.',
    exampleVi: 'Tôi bị đau đầu khủng khiếp cả buổi sáng.',
    synonyms: 'migraine (severe headache)',
    antonyms: '(Blank)',
    collocations: 'terrible headache, suffer from a headache, cure a headache',
    toeicTrap: '(Blank)',
  },
  {
    word: 'Stomach',
    phonetic: '/ˈstʌmək/',
    meaning: 'Dạ dày, bụng',
    englishDefinition: 'The internal organ in which the major part of the digestion of food occurs.',
    example: 'You shouldn\'t take this medicine on an empty stomach.',
    exampleVi: 'Bạn không nên uống loại thuốc này khi bụng đói.',
    synonyms: 'belly, tummy',
    antonyms: '(Blank)',
    collocations: 'empty stomach, upset stomach, stomach ache',
    toeicTrap: '(Blank)',
  },
  {
    word: 'Temperature',
    phonetic: '/ˈtemprətʃər/',
    meaning: 'Nhiệt độ (cơ thể)',
    englishDefinition: 'The degree of internal heat of a person\'s body.',
    example: 'The nurse took my temperature and blood pressure.',
    exampleVi: 'Y tá đã đo nhiệt độ và huyết áp cho tôi.',
    synonyms: 'heat, fever',
    antonyms: '(Blank)',
    collocations: 'take temperature, high temperature, body temperature',
    toeicTrap: 'Trong y tế, "have a temperature" đồng nghĩa với "bị sốt" (have a fever).',
  },
  {
    word: 'Weight',
    phonetic: '/weɪt/',
    meaning: 'Cân nặng',
    englishDefinition: 'A body\'s relative mass or the quantity of matter contained by it.',
    example: 'The doctor advised him to lose some weight.',
    exampleVi: 'Bác sĩ khuyên anh ấy nên giảm cân một chút.',
    synonyms: 'mass, heaviness',
    antonyms: '(Blank)',
    collocations: 'lose weight, gain weight, put on weight',
    toeicTrap: 'Khác với "weigh" (động từ: cân).',
  },
  {
    word: 'Emergency',
    phonetic: '/ɪˈmɜːrdʒənsi/',
    meaning: 'Tình trạng khẩn cấp',
    englishDefinition: 'A serious, unexpected, and often dangerous situation requiring immediate action.',
    example: 'The hospital has an emergency generator in case of power failure.',
    exampleVi: 'Bệnh viện có máy phát điện khẩn cấp trong trường hợp mất điện.',
    synonyms: 'crisis, urgency',
    antonyms: '(Blank)',
    collocations: 'emergency room, medical emergency, in case of emergency',
    toeicTrap: '(Blank)',
  },

  // 8 Advanced
  {
    word: 'Prescribe',
    phonetic: '/prɪˈskraɪb/',
    meaning: 'Kê đơn (thuốc)',
    englishDefinition: '(Of a medical practitioner) advise and authorize the use of (a medicine or treatment) for someone.',
    example: 'The doctor will prescribe some painkillers for your back.',
    exampleVi: 'Bác sĩ sẽ kê một số loại thuốc giảm đau cho lưng của bạn.',
    synonyms: 'recommend, authorize, direct',
    antonyms: '(Blank)',
    collocations: 'prescribe medicine, prescribe antibiotics',
    toeicTrap: 'Đây là động từ của "prescription". Đừng nhầm với "subscribe" (đăng ký theo dõi).',
  },
  {
    word: 'Recover',
    phonetic: '/rɪˈkʌvər/',
    meaning: 'Hồi phục',
    englishDefinition: 'Return to a normal state of health, mind, or strength.',
    example: 'It took her a few weeks to fully recover from the surgery.',
    exampleVi: 'Cô ấy mất vài tuần để hồi phục hoàn toàn sau ca phẫu thuật.',
    synonyms: 'get well, heal, bounce back',
    antonyms: 'deteriorate, worsen',
    collocations: 'fully recover, recover from an illness, fast recovery',
    toeicTrap: '(Blank)',
  },
  {
    word: 'Examine',
    phonetic: '/ɪɡˈzæmɪn/',
    meaning: 'Khám bệnh, kiểm tra',
    englishDefinition: 'Inspect (someone or something) in detail to determine their nature or condition.',
    example: 'The physician will examine you shortly.',
    exampleVi: 'Bác sĩ sẽ khám cho bạn ngay bây giờ.',
    synonyms: 'inspect, investigate, check',
    antonyms: '(Blank)',
    collocations: 'examine a patient, medically examined',
    toeicTrap: '(Blank)',
  },
  {
    word: 'Remedy',
    phonetic: '/ˈremədi/',
    meaning: 'Phương thuốc, biện pháp cứu chữa',
    englishDefinition: 'A medicine or treatment for a disease or injury.',
    example: 'Herbal tea is a popular home remedy for a cold.',
    exampleVi: 'Trà thảo mộc là một phương thuốc dân gian phổ biến cho bệnh cảm lạnh.',
    synonyms: 'cure, treatment, solution',
    antonyms: '(Blank)',
    collocations: 'home remedy, effective remedy, herbal remedy',
    toeicTrap: '(Blank)',
  },
  {
    word: 'Ward',
    phonetic: '/wɔːrd/',
    meaning: 'Phòng bệnh, khu bệnh',
    englishDefinition: 'A separate room in a hospital, typically one allocated to a particular type of patient.',
    example: 'She works as a nurse in the maternity ward.',
    exampleVi: 'Cô ấy làm y tá ở khoa sản.',
    synonyms: 'room, department, unit',
    antonyms: '(Blank)',
    collocations: 'maternity ward, emergency ward, hospital ward',
    toeicTrap: '(Blank)',
  },
  {
    word: 'Sanitation',
    phonetic: '/ˌsænɪˈteɪʃn/',
    meaning: 'Hệ thống vệ sinh',
    englishDefinition: 'Conditions relating to public health, especially the provision of clean drinking water and adequate sewage disposal.',
    example: 'Disease can spread quickly in areas with poor sanitation.',
    exampleVi: 'Bệnh tật có thể lây lan nhanh chóng ở những khu vực có hệ thống vệ sinh kém.',
    synonyms: 'hygiene, cleanliness',
    antonyms: '(Blank)',
    collocations: 'poor sanitation, improve sanitation',
    toeicTrap: '(Blank)',
  },
  {
    word: 'Outpatient',
    phonetic: '/ˈaʊtpeɪʃnt/',
    meaning: 'Bệnh nhân ngoại trú',
    englishDefinition: 'A patient who attends a hospital for treatment without staying there overnight.',
    example: 'The outpatient clinic is open from 8 AM to 5 PM.',
    exampleVi: 'Phòng khám ngoại trú mở cửa từ 8 giờ sáng đến 5 giờ chiều.',
    synonyms: '(Blank)',
    antonyms: 'inpatient',
    collocations: 'outpatient clinic, outpatient care, outpatient treatment',
    toeicTrap: '(Blank)',
  },
  {
    word: 'Contagious',
    phonetic: '/kənˈteɪdʒəs/',
    meaning: 'Lây nhiễm',
    englishDefinition: '(Of a disease) spread from one person or organism to another by direct or indirect contact.',
    example: 'The flu is highly contagious, so you should stay home.',
    exampleVi: 'Cúm rất dễ lây lan, vì vậy bạn nên ở nhà.',
    synonyms: 'infectious, transmissible, catching',
    antonyms: 'non-communicable',
    collocations: 'highly contagious, contagious disease',
    toeicTrap: '(Blank)',
  }
];

async function insertPackage(topicName: string, packageType: 'BASIC' | 'ADVANCED' | 'MIXED', vocabs: any[]) {
  const topicString = `Health & Medicine - Y tế & Sức khỏe - ${topicName}`;
  
  // 1. Check or create config
  await prisma.vocabularyTopicConfig.upsert({
    where: { topic: topicString },
    update: { packageType },
    create: {
      topic: topicString,
      packageType,
      proFields: JSON.stringify(['synonyms', 'antonyms', 'collocations']),
      ultraFields: JSON.stringify(['toeicTrap']),
    }
  });

  // 2. Clear old vocabs if exist
  await prisma.vocabularyItem.deleteMany({
    where: { topic: topicString }
  });

  // 3. Insert vocabs
  for (let i = 0; i < vocabs.length; i++) {
    const v = vocabs[i];
    await prisma.vocabularyItem.create({
      data: {
        word: v.word,
        phonetic: v.phonetic,
        meaning: v.meaning,
        englishDefinition: v.englishDefinition,
        example: v.example,
        exampleVi: v.exampleVi,
        topic: topicString,
        displayOrder: i + 1,
        category: 'TOEIC',
        synonyms: v.synonyms,
        antonyms: v.antonyms,
        collocations: v.collocations,
        toeicTrap: v.toeicTrap,
        isActive: true,
      }
    });
  }
  
  console.log(`Inserted ${vocabs.length} words for ${topicString}`);
}

async function main() {
  await insertPackage('Cơ bản', 'BASIC', basicVocabs);
  await insertPackage('Nâng cao', 'ADVANCED', advancedVocabs);
  await insertPackage('Hỗn hợp', 'MIXED', mixedVocabs);
}

main()
  .catch(e => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
